### ISSUE TITLE
read config.json from home dir

### ISSUE THREAD

**Issue by hennr** [PH1P5/cctron#2]
Hi there,

would be nice to read the config.json with the build chain URLs from the user's home dir e.g. ~/.config/cctron/config.json under linux.
This way teams could share config.json files.

There is a standard for that as well called XDG: https://freedesktop.org/wiki/Software/xdg-user-dirs/

**Comment by PH1P5** [comment]
Hi @hennr 

please have a look if [this](https://github.com/PH1P5/cctron/commit/cdc0a37d8cf9f6f01570a3b205e30515482de612) fits your needs ;). I will adjust the README later.

**Comment by PH1P5** [comment]
has been fixed some time ago
